# Generated by Django 5.1.2 on 2024-10-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='imagem',
            field=models.ImageField(default=1, upload_to='pratos/'),
            preserve_default=False,
        ),
    ]
