# Generated by Django 5.1.3 on 2024-11-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
