# Generated by Django 5.1.3 on 2024-11-22 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_remove_pedido_cliente_remove_reserva_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='prato',
            name='categoria',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(default='Anônimo', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prato',
            field=models.ForeignKey(default='Anônimo', on_delete=django.db.models.deletion.CASCADE, to='aplic.prato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.PositiveIntegerField(default='Anônimo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prato',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prato',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bebida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.bebida'),
        ),
    ]
